-- Append-only audit ledger.
--
-- Grant the application user INSERT and SELECT only. The repository interface exposes
-- no update or delete method, but enforce it at the grant as well, so a compromised
-- application still cannot rewrite its own history:
--
--   GRANT INSERT, SELECT ON PAYMENT_AUDIT_EVENTS TO PAYMENT_APP;
--
-- Retention: confirm the applicable figure with compliance before scheduling a purge,
-- and run the purge from a separate privileged job, never from the application.

CREATE TABLE PAYMENT_AUDIT_EVENTS (
    ID               NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CORRELATION_ID   VARCHAR2(36)  NOT NULL,
    EVENT_TYPE       VARCHAR2(48)  NOT NULL,
    OUTCOME          VARCHAR2(16)  NOT NULL,
    ERROR_CODE       VARCHAR2(48),
    SESSION_REF      VARCHAR2(32),
    AGREEMENT_NUMBER VARCHAR2(50),
    CLIENT_IP_HASH   VARCHAR2(32),
    USER_AGENT       VARCHAR2(256),
    OCCURRED_AT      TIMESTAMP     NOT NULL
)
PARTITION BY RANGE (OCCURRED_AT)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(PARTITION P_INITIAL VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'));

CREATE INDEX IX_AUDIT_CORRELATION ON PAYMENT_AUDIT_EVENTS (CORRELATION_ID) LOCAL;
CREATE INDEX IX_AUDIT_AGREEMENT   ON PAYMENT_AUDIT_EVENTS (AGREEMENT_NUMBER, OCCURRED_AT) LOCAL;
