-- Full record of every upstream call, replacing the legacy goldLogDetails table.
--
-- Request and response bodies are stored in full because reconciliation and dispute
-- handling need the exact payload the LMS returned. This is the right home for them:
-- the grant and the retention here are yours to set, unlike a log aggregator's.
--
--   GRANT INSERT, SELECT ON LMS_INTERACTION_LOG TO PAYMENT_APP;
--
-- Interval partitioning is not optional at volume: the CLOB columns make this the
-- largest table in the schema, and a monthly purge without partitions means a very
-- expensive DELETE. With partitions it is a DROP PARTITION.
--
-- SMS rows never contain the OTP. The endpoint and response have the code and mobile
-- number redacted before the row is written.

CREATE TABLE LMS_INTERACTION_LOG (
    ID               NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CORRELATION_ID   VARCHAR2(36)  NOT NULL,
    INTERACTION_TYPE VARCHAR2(32)  NOT NULL,
    ENDPOINT         VARCHAR2(512) NOT NULL,
    HTTP_METHOD      VARCHAR2(8)   NOT NULL,
    AGREEMENT_NUMBER VARCHAR2(50),
    REQUEST_BODY     CLOB,
    RESPONSE_BODY    CLOB,
    HTTP_STATUS      NUMBER(5),
    UPSTREAM_STATUS  VARCHAR2(64),
    UPSTREAM_CODE    VARCHAR2(32),
    OUTCOME          VARCHAR2(16)  NOT NULL,
    ERROR_DETAIL     VARCHAR2(512),
    DURATION_MS      NUMBER(19),
    REQUESTED_AT     TIMESTAMP     NOT NULL,
    RESPONDED_AT     TIMESTAMP
)
PARTITION BY RANGE (REQUESTED_AT)
INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(PARTITION P_INITIAL VALUES LESS THAN (TIMESTAMP '2026-01-01 00:00:00'));

CREATE INDEX IX_LMS_CORRELATION ON LMS_INTERACTION_LOG (CORRELATION_ID) LOCAL;
CREATE INDEX IX_LMS_AGREEMENT   ON LMS_INTERACTION_LOG (AGREEMENT_NUMBER, REQUESTED_AT) LOCAL;
CREATE INDEX IX_LMS_TYPE        ON LMS_INTERACTION_LOG (INTERACTION_TYPE, REQUESTED_AT) LOCAL;
